sudo: required

notifications:
  slack: ebayclassifiedsgroup:tFHOcsnmbj9SKmfquoJJKjSb

language: ruby
ruby:
- 2.2

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv F76221572C52609D
  - echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list
  - sudo apt-get update
  - sudo apt-get -q -y install linux-image-extra-$(uname -r)
  - sudo apt-get -q -y install docker-engine=1.7.1-0~trusty
  - sudo apt-get install -y curl python-pip ruby-dev
  - sudo pip install pip --upgrade
  - sudo pip install docker-compose --upgrade
  - gem install marathon_deploy
  - ./build-docker-images.sh
  - export IP=$(/sbin/ifconfig eth0 | awk '/inet addr:/{gsub(/.*:/,"",$2);print $2;exit}')
  - echo $IP
  - export START_DNSMASQ=false
  - export ZOOKEEPER_HOSTS=${IP}:2181
  - ./generate_yml.sh
  - cat docker-compose.yml
  - sudo netstat -tulpen
  - docker --version
  - docker-compose up -d

script:
  - docker ps
  - sleep 10
  - docker exec -ti panteras_panteras_1 supervisorctl status
  - cd examples/SimpleWebappPython
  - ./test_service.sh
