sudo: required

#notifications:
#  slack: ebayclassifiedsgroup:WQ6qXgtYQwyIfuu8KI7DnVxb

language: ruby

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl python-pip
  - sudo pip install pip --upgrade
  - sudo pip install docker-compose --upgrade
  - #./build-docker-images.sh
  - export IP=$(/sbin/ifconfig eth0 | awk '/inet addr:/{gsub(/.*:/,"",$2);print $2;exit}')
  - echo $IP
  - export START_DNSMASQ=false
  - export ZOOKEEPER_HOSTS=${IP}:2181
  - TEST_SERVICE=$(echo curl --fail -H 'Host python.service.consul' $IP)
  - echo $TEST_SERVICE
  - ./generate_yml.sh
  - cat docker-compose.yml
  - sudo netstat -tulpen
  - #docker-compose up -d

script:
  - docker ps
  - sleep 5
  - docker exec -ti panteras_panteras_1 supervisorctl status
  - sleep 5
  - docker logs --tail=4000 panteras_panteras_1
  - sudo netstat -tulpen
  - cd examples/SimpleWebappPython
  - ./start_with_marathon.sh deploy0_marathon.json
  - sleep 5
  - docker ps
  - docker exec -ti panteras_panteras_1 supervisorctl status
  - $TEST_SERVICE
