language: bash

sudo: required
services: docker 

notifications:
  slack: ebayclassifiedsgroup:tFHOcsnmbj9SKmfquoJJKjSb

before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl python-pip ruby-dev build-essential python-dev
  - sudo pip install pip --upgrade
  - sudo pip install docker-compose --upgrade
  - gem install marathon_deploy
  - docker pull ubuntu:14.04
  - ./build-docker-images.sh
#  - docker pull panteras/paas-in-a-box:latest
  - export IP=$(/sbin/ifconfig eth0 | awk '/inet addr:/{gsub(/.*:/,"",$2);print $2;exit}')
  - echo $IP
  - export START_DNSMASQ=false
  - export ZOOKEEPER_HOSTS=${IP}:2181
  - ./generate_yml.sh
  - cat docker-compose.yml
  - sudo netstat -tulpen
  - docker --version
  - docker images
  - docker-compose up -d

script:
  - docker ps
  - sleep 10
  - docker exec -ti panteras_panteras_1 supervisorctl status
  - cd examples/SimpleWebappPython
  - ./test_service.sh
